// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'slack_message_file_entity.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_SlackMessageFileEntity _$SlackMessageFileEntityFromJson(
  Map<String, dynamic> json,
) => _SlackMessageFileEntity(
  id: json['id'] as String?,
  created: (json['created'] as num?)?.toInt(),
  timestamp: (json['timestamp'] as num?)?.toInt(),
  name: json['name'] as String?,
  title: json['title'] as String?,
  mimetype: json['mimetype'] as String?,
  filetype: json['filetype'] as String?,
  prettyType: json['pretty_type'] as String?,
  user: json['user'] as String?,
  userTeam: json['user_team'] as String?,
  editable: json['editable'] as bool?,
  size: (json['size'] as num?)?.toInt(),
  mode: json['mode'] as String?,
  isExternal: json['is_external'] as bool?,
  isPublic: json['is_public'] as bool?,
  publicUrlShared: json['public_url_shared'] as bool?,
  displayAsBot: json['display_as_bot'] as bool?,
  username: json['username'] as String?,
  urlPrivate: json['url_private'] as String?,
  urlPrivateDownload: json['url_private_download'] as String?,
  mediaDisplayType: json['media_display_type'] as String?,
  thumb_64: json['thumb_64'] as String?,
  thumb_80: json['thumb_80'] as String?,
  thumb_160: json['thumb_160'] as String?,
  thumb_360: json['thumb_360'] as String?,
  thumb_360_w: (json['thumb_360_w'] as num?)?.toInt(),
  thumb_360_h: (json['thumb_360_h'] as num?)?.toInt(),
  thumb_480: json['thumb_480'] as String?,
  thumb_480_w: (json['thumb_480_w'] as num?)?.toInt(),
  thumb_480_h: (json['thumb_480_h'] as num?)?.toInt(),
  thumb_720: json['thumb_720'] as String?,
  thumb_720_w: (json['thumb_720_w'] as num?)?.toInt(),
  thumb_720_h: (json['thumb_720_h'] as num?)?.toInt(),
  thumb_800: json['thumb_800'] as String?,
  thumb_800_w: (json['thumb_800_w'] as num?)?.toInt(),
  thumb_800_h: (json['thumb_800_h'] as num?)?.toInt(),
  thumb_960: json['thumb_960'] as String?,
  thumb_960_w: (json['thumb_960_w'] as num?)?.toInt(),
  thumb_960_h: (json['thumb_960_h'] as num?)?.toInt(),
  thumb_1024: json['thumb_1024'] as String?,
  thumb_1024_w: (json['thumb_1024_w'] as num?)?.toInt(),
  thumb_1024_h: (json['thumb_1024_h'] as num?)?.toInt(),
  thumb_video: json['thumb_video'] as String?,
  thumb_video_w: (json['thumb_video_w'] as num?)?.toInt(),
  thumb_video_h: (json['thumb_video_h'] as num?)?.toInt(),
  original_w: (json['original_w'] as num?)?.toInt(),
  original_h: (json['original_h'] as num?)?.toInt(),
  thumbTiny: json['thumb_tiny'] as String?,
  permalink: json['permalink'] as String?,
  permalinkPublic: json['permalink_public'] as String?,
  isStarred: json['is_starred'] as bool?,
  hasRichPreview: json['has_rich_preview'] as bool?,
  fileAccess: json['file_access'] as String?,
);

Map<String, dynamic> _$SlackMessageFileEntityToJson(
  _SlackMessageFileEntity instance,
) => <String, dynamic>{
  'id': ?instance.id,
  'created': ?instance.created,
  'timestamp': ?instance.timestamp,
  'name': ?instance.name,
  'title': ?instance.title,
  'mimetype': ?instance.mimetype,
  'filetype': ?instance.filetype,
  'pretty_type': ?instance.prettyType,
  'user': ?instance.user,
  'user_team': ?instance.userTeam,
  'editable': ?instance.editable,
  'size': ?instance.size,
  'mode': ?instance.mode,
  'is_external': ?instance.isExternal,
  'is_public': ?instance.isPublic,
  'public_url_shared': ?instance.publicUrlShared,
  'display_as_bot': ?instance.displayAsBot,
  'username': ?instance.username,
  'url_private': ?instance.urlPrivate,
  'url_private_download': ?instance.urlPrivateDownload,
  'media_display_type': ?instance.mediaDisplayType,
  'thumb_64': ?instance.thumb_64,
  'thumb_80': ?instance.thumb_80,
  'thumb_160': ?instance.thumb_160,
  'thumb_360': ?instance.thumb_360,
  'thumb_360_w': ?instance.thumb_360_w,
  'thumb_360_h': ?instance.thumb_360_h,
  'thumb_480': ?instance.thumb_480,
  'thumb_480_w': ?instance.thumb_480_w,
  'thumb_480_h': ?instance.thumb_480_h,
  'thumb_720': ?instance.thumb_720,
  'thumb_720_w': ?instance.thumb_720_w,
  'thumb_720_h': ?instance.thumb_720_h,
  'thumb_800': ?instance.thumb_800,
  'thumb_800_w': ?instance.thumb_800_w,
  'thumb_800_h': ?instance.thumb_800_h,
  'thumb_960': ?instance.thumb_960,
  'thumb_960_w': ?instance.thumb_960_w,
  'thumb_960_h': ?instance.thumb_960_h,
  'thumb_1024': ?instance.thumb_1024,
  'thumb_1024_w': ?instance.thumb_1024_w,
  'thumb_1024_h': ?instance.thumb_1024_h,
  'thumb_video': ?instance.thumb_video,
  'thumb_video_w': ?instance.thumb_video_w,
  'thumb_video_h': ?instance.thumb_video_h,
  'original_w': ?instance.original_w,
  'original_h': ?instance.original_h,
  'thumb_tiny': ?instance.thumbTiny,
  'permalink': ?instance.permalink,
  'permalink_public': ?instance.permalinkPublic,
  'is_starred': ?instance.isStarred,
  'has_rich_preview': ?instance.hasRichPreview,
  'file_access': ?instance.fileAccess,
};
