// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1kBy4mvHzhygq381ueCpe0Ydq8nJ9Xuw',
    appId: '1:939046847033:web:b90f4c7e9f7add8b4603e8',
    messagingSenderId: '939046847033',
    projectId: 'fillin-cd65f',
    authDomain: 'fillin-cd65f.firebaseapp.com',
    storageBucket: 'fillin-cd65f.appspot.com',
    measurementId: 'G-YPMWTYJZ2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQVyB9EhDtKfSRKuGicsdj86dO0cwE-uQ',
    appId: '1:939046847033:android:b15e593b02a86d394603e8',
    messagingSenderId: '939046847033',
    projectId: 'fillin-cd65f',
    storageBucket: 'fillin-cd65f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlKQA1IhgdRq7EmuGy1NIr6m67qksVr74',
    appId: '1:939046847033:ios:2eb599bb968912da4603e8',
    messagingSenderId: '939046847033',
    projectId: 'fillin-cd65f',
    storageBucket: 'fillin-cd65f.appspot.com',
    androidClientId: '939046847033-1ft3h2jjfflsvf4jbb19jd651mkc06jk.apps.googleusercontent.com',
    iosClientId: '939046847033-g7h3911n6nkaa2rd0477p05evos6ulq9.apps.googleusercontent.com',
    iosBundleId: 'com.wavetogether.fillin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlKQA1IhgdRq7EmuGy1NIr6m67qksVr74',
    appId: '1:939046847033:ios:2eb599bb968912da4603e8',
    messagingSenderId: '939046847033',
    projectId: 'fillin-cd65f',
    storageBucket: 'fillin-cd65f.appspot.com',
    androidClientId: '939046847033-1ft3h2jjfflsvf4jbb19jd651mkc06jk.apps.googleusercontent.com',
    iosClientId: '939046847033-g7h3911n6nkaa2rd0477p05evos6ulq9.apps.googleusercontent.com',
    iosBundleId: 'com.wavetogether.fillin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw_MNRP_TEyd1A6jIv5G81rPX8k375kqg',
    appId: '1:939046847033:web:2ed643faf30b89864603e8',
    messagingSenderId: '939046847033',
    projectId: 'fillin-cd65f',
    authDomain: 'fillin-cd65f.firebaseapp.com',
    storageBucket: 'fillin-cd65f.appspot.com',
    measurementId: 'G-DNTTKD4ZV4',
  );

}